project_path: "/home/tmassagl/development/astrodata_examples"

code:
  enable: true
  auto_commit: true
  tracked_files: ["examples"]
  commit_message: "Auto commit by astrodata"
  branch: "test_branch"
  remote:
    enable: true
    name: "origin"
    url: "https://github.com/tommasomassaglia/astrotaxi_example.git"
  #ssh_key_path: ""
  token: "/home/tmassagl/development/astrodata_examples/pac_token.pem"  # Optional

data:
  enable: true
  paths:
    - "testdata"
  remote: "/home/tmassagl/development/astrodata_dvc" # Must be full path
  push: true

preml:
  TrainTestSplitter:
    targets:
      - "duration"
    test_size: 0.2
    random_state: 42
    validation:
      enabled: false
      size: 0.1